// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsroDX86kNW04aXpAuv2VwKSYldGfn91w',
    appId: '1:688165065706:android:7975f27907b7115f3f9893',
    messagingSenderId: '688165065706',
    projectId: 'mathhelper-community',
    databaseURL: 'https://mathhelper-community.firebaseio.com',
    storageBucket: 'mathhelper-community.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKO3cw32V5-VO67fU4c9KCOlaQ1Vb5-nU',
    appId: '1:688165065706:ios:2e1e6169b3524b123f9893',
    messagingSenderId: '688165065706',
    projectId: 'mathhelper-community',
    databaseURL: 'https://mathhelper-community.firebaseio.com',
    storageBucket: 'mathhelper-community.appspot.com',
    iosClientId: '688165065706-21245ckakam9fjamn2k90veu9qs782ab.apps.googleusercontent.com',
    iosBundleId: 'mathhelper.games.mathGameCrossplatform',
  );
}
